<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageTheatre.aspx.cs" Inherits="BookMyShow.ManageTheatre" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Theatre</title>
    <link rel="stylesheet" href="Style/admin.css" />
    <style>
        .success {
            font-size: 12px;
            color: green;
        }
        .error {
            font-size: 12px;
            color: red;
        }
        .display {
            margin: 0 270px;
            max-height: 300px;
            overflow-y: auto;
            overflow-x: auto;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            width: 50%;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
            <div class="sidebar">
              <div class="menu">
                <div class="menu-option"><a href="ManageUsers.aspx">Users</a></div>
                <div class="menu-option target"><a href="ManageTheatre.aspx">Manage Theatre</a></div>
                <div class="menu-option"><a href="ManageMovies.aspx">Manage Movies</a></div>
                <div class="menu-option"><a href="ManageShows.aspx">Manage Shows</a></div>
                <div class="menu-option"><a href="AdminPanel.aspx" class="settings">Admin 📱</a></div>
              </div>
            </div>
            <div class="main-content">
              <div class="form">
                <h2>Manage Theatre</h2>
                <div class="form-group">
                  <asp:Label ID="theatreNameLB" runat="server" class="label" Text="Theatre name:"></asp:Label>
                  <asp:TextBox ID="theatreNameTxt" class="input" runat="server"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="theatreNameTxt" CssClass="error" Display="Dynamic" ErrorMessage="Theatre name is required"></asp:RequiredFieldValidator>
                </div>
                <div class="form-group">
                  <asp:Label ID="locationLB" runat="server" class="label" Text="Location:"></asp:Label>
                  <asp:DropDownList ID="locationDDL" runat="server" class="input" AutoPostBack="True">
                      <asp:ListItem>Surat</asp:ListItem>
                      <asp:ListItem>Pune</asp:ListItem>
                      <asp:ListItem>Mumbai</asp:ListItem>
                      <asp:ListItem>Ahemdabad</asp:ListItem>
                      <asp:ListItem>Delhi</asp:ListItem>
                      <asp:ListItem>Chennai</asp:ListItem>
                      <asp:ListItem>Kolkata</asp:ListItem>
                    </asp:DropDownList>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="locationDDL" CssClass="error" Display="Dynamic" ErrorMessage="Location is required"></asp:RequiredFieldValidator>
                </div>
                <div class="form-group">
                  <asp:Label ID="totalSeatsLB" runat="server" class="label" Text="Total Seats:"></asp:Label>
                  <asp:TextBox ID="totalSeatsTxt" class="input" runat="server" TextMode="Number"></asp:TextBox>
                    <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="totalSeatsTxt" CssClass="error" Display="Dynamic" ErrorMessage="Total seats is required"></asp:RequiredFieldValidator>
                </div>
                <asp:Label ID="successLB" runat="server" Text="" CssClass="success"></asp:Label>
                <asp:Label ID="errorLB" runat="server" Text="" CssClass="error"></asp:Label>
                <div class="btns">
                    <asp:Button ID="submitBtn" runat="server" Text="Submit" class="button" OnClick="submitBtn_Click" />
                    <asp:Button ID="clearBtn" runat="server" Text="Clear" class="button" OnClick="clearBtn_Click" />
                    <asp:Button ID="editBtn" runat="server" Text="Edit" class="button" OnClick="editBtn_Click" />
                </div>
              </div>
            </div>
            <div class="display">
                <asp:GridView ID="dgvTheatre" runat="server" BackColor="White" BorderStyle="None" BorderWidth="1px" CellPadding="12" ForeColor="Black" GridLines="Horizontal" Width="500px" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="dgvTheatre_SelectedIndexChanged" OnRowDeleting="dgvTheatre_RowDeleting">
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                </asp:GridView>
            </div>
        </div>
    </form>
</body>
</html>
