<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageUsers.aspx.cs" Inherits="BookMyShow.ManageUsers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Users</title>
    <link rel="stylesheet" href="Style/admin.css" />
    <style>
        .display {
            margin: 0 270px;
            max-height: 300px;
            overflow-y: auto;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            width: 100%;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
    <div class="sidebar">
      <div class="menu">
        <div class="menu-option target"><a href="ManageUsers.aspx">Users</a></div>
        <div class="menu-option"><a href="ManageTheatre.aspx">Manage Theatre</a></div>
        <div class="menu-option"><a href="ManageMovies.aspx">Manage Movies</a></div>
        <div class="menu-option"><a href="ManageShows.aspx">Manage Shows</a></div>
        <div class="menu-option"><a href="AdminPanel.aspx" class="settings">Admin 📱</a></div>
      </div>
    </div>
    <div class="main-content">
      <div class="form">
         <div class="display">
             <asp:GridView ID="dgvUser" runat="server" BackColor="White" BorderStyle="None" BorderWidth="1px" CellPadding="12" ForeColor="Black" GridLines="Horizontal" Width="727px" AutoGenerateDeleteButton="True"  >
                 <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                 <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
                 <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                 <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                 <SortedAscendingCellStyle BackColor="#F7F7F7" />
                 <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                 <SortedDescendingCellStyle BackColor="#E5E5E5" />
                 <SortedDescendingHeaderStyle BackColor="#242121" />
             </asp:GridView>
         </div>
   
      </div>
    </div>
    <div>
        <asp:GridView ID="dgvUsers" runat="server"></asp:GridView>
    </div>
</div>
    </form>
</body>
</html>
