<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageShows.aspx.cs" Inherits="BookMyShow.ManageShows" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Shows</title>
    <link rel="stylesheet" href="Style/admin.css" />
    <style>
        .success {
            font-size: 12px;
            color: green;
        }
        .error {
            font-size: 12px;
            color: red;
        }
        .display {
            margin: 0 270px;
            max-height: 300px;
            overflow-y: auto;
            display: flex;
            justify-content: flex-start;
            align-items: center;
            width: 100%;
            text-align: center;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div class="container">
    <div class="sidebar">
      <div class="menu">
        <div class="menu-option"><a href="ManageUsers.aspx">Users</a></div>
        <div class="menu-option"><a href="ManageTheatre.aspx">Manage Theatre</a></div>
        <div class="menu-option"><a href="ManageMovies.aspx">Manage Movies</a></div>
        <div class="menu-option target"><a href="ManageShows.aspx">Manage Shows</a></div>
        <div class="menu-option"><a href="AdminPanel.aspx" class="settings">Admin 📱</a></div>
      </div>
    </div>
    <div class="main-content">
      <div class="form">
        <h2>Manage Shows</h2>
        <div class="form-group">
          <asp:Label ID="movieLB" runat="server" class="label" Text="Movie:"></asp:Label>
          <asp:DropDownList ID="movieDDL" runat="server" class="input"></asp:DropDownList>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="movieDDL" CssClass="error" ErrorMessage="Movie is required"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
          <asp:Label ID="theatreLB" runat="server" class="label" Text="Theatre:"></asp:Label>
          <asp:DropDownList ID="theatreDDL" runat="server" class="input"></asp:DropDownList>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="theatreDDL" CssClass="error" ErrorMessage="Theatre is required"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
          <asp:Label ID="showTimeLB" runat="server" class="label" Text="Show Time:"></asp:Label>
          <asp:TextBox ID="showTimeTxt" class="input" runat="server" TextMode="Date"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="showTimeTxt" CssClass="error" ErrorMessage="Show time is required"></asp:RequiredFieldValidator>
        </div>
        <div class="form-group">
          <asp:Label ID="priceLB" runat="server" class="label" Text="Price:"></asp:Label>
          <asp:TextBox ID="priceTxt" class="input" runat="server" TextMode="Number"></asp:TextBox>
            <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="priceTxt" CssClass="error" ErrorMessage="Price is required"></asp:RequiredFieldValidator>
        </div>
          <asp:Label ID="successLB" runat="server" Text="" CssClass="success"></asp:Label>
          <asp:Label ID="errorLB" runat="server" Text="" CssClass="error"></asp:Label>
        <div class="btns">
            <asp:Button ID="submitBtn" runat="server" Text="Submit" class="button" OnClick="submitBtn_Click" />
            <asp:Button ID="clearBtn" runat="server" Text="Clear" class="button" OnClick="clearBtn_Click" />
            <asp:Button ID="editBtn" runat="server" Text="Edit" class="button" OnClick="editBtn_Click" />
        </div>
      </div>
    </div>

    <div class="display">
        <asp:GridView ID="dgvShows" runat="server" BackColor="White" BorderStyle="None" BorderWidth="1px" CellPadding="12" ForeColor="Black" GridLines="Horizontal" Width="727px" AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" OnSelectedIndexChanged="dgvShows_SelectedIndexChanged" OnRowDeleting="dgvShows_RowDeleting" >
            <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
            <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
            <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F7F7F7" />
            <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
            <SortedDescendingCellStyle BackColor="#E5E5E5" />
            <SortedDescendingHeaderStyle BackColor="#242121" />
        </asp:GridView>
    </div>
    </div>
    </form>
</body>
</html>
